
(* terminals *)

COUNTERCHANGED
    = #"\bcounterchanged\b"
    | #"\bde +l'un +[aà] +l'autre\b"
    | #"\binterchanged\b"

FIMBRIATED
    = #"\bfimbriated\b"
    | #"\bfimbrated\b"
    | #"\bfimbriation\b"

A = #"\ba\b"
  | #"\ban\b"
<AND> = #"\band\b"
    | #"&"
    | #","
IN = #"\bin\b"
AT = #"\bat\b"
OF = #"\bof\b"
ON = #"\bon\b"
THE = #"\bthe\b"
LIKE = #"\blike\b"
WITH = #"\bwith\b"
CHARGED = #"\bcharged\b"
TRACTS = #"\btracts\b"
X = #"x"
TIMES = #"\btimes\b"
TINCTURE = #"\btincture\b"
FIELD
    = #"\bfield\b"
    | #"\bchamp\b"

SAME = #"\bsame\b"
POINT = #"\bpoint\b"
SEMY
    = #"\bsemy\b"
    | #"\bsem[ée](?=([ ,&]|$))"
    | #"\bsem[ée]e\b"

DOUBLY
    = #"\bdoubly\b"
    | #"\bdouble\b"
    | #"\btwo\b"
    | #"\b2\b"
BETWEEN
    = #"\bbetween\b"
    | #"\bbeside\b"
    | #"\bbetwixt\b"
    | #"\bbetwyxt\b"

COTTISED
    = #"\bcottised\b"
    | #"\bcotticed\b"
    | #"\bcottises\b"
    | #"\bcottices\b"
    | #"\bcottising\b"
    | #"\bcotticing\b"
    | #"\bbendorsed\b"
    | #"\bbendorsing\b"
    | #"\bcosts\b"
    | #"\bendorsed\b"
    | #"\blined\b"
    | #"\bcotices\b"
    | #"\bcotissed\b"
    | #"\bcottizes\b"
    | #"\bcotised\b"

number/NUMBER = #"[1-9][0-9]*"
number/DIGIT-WORD
    = #"\bone\b"
    | #"\btwo\b"
    | #"\bthree\b"
    | #"\bfour\b"
    | #"\bfive\b"
    | #"\bsix\b"
    | #"\bseven\b"
    | #"\beight\b"
    | #"\bnine\b"
number/MULTI-WORD
    = #"\bdouble\b"
    | #"\btriple\b"
number/TEEN-WORD
    = #"\bten\b"
    | #"\beleven\b"
    | #"\btwelve\b"
    | #"\bthirteen\b"
    | #"\bfourteen\b"
    | #"\bfifteen\b"
    | #"\bsixteen\b"
    | #"\bseventeen\b"
    | #"\beighteen\b"
    | #"\bnineteen\b"
number/MULTIPLE-OF-TEN-WORD
    = #"\btwenty\b"
    | #"\bthirty\b"
    | #"\bfourty\b"
    | #"\bfifty\b"
    | #"\bsixty\b"
    | #"\bseventy\b"
    | #"\beighty\b"
    | #"\bninety\b"

ordinal/NUMBER
    = #"\b1st\b"
    | #"\b2nd\b"
    | #"\b3rd\b"
    | #"\b4th\b"
    | #"\b5th\b"
    | #"\b6th\b"
    | #"\b7th\b"
    | #"\b8th\b"
    | #"\b9th\b"
    | #"\b10th\b"
    | #"\b11th\b"
    | #"\b12th\b"
    | #"\b13th\b"
    | #"\b14th\b"
    | #"\b15th\b"
    | #"\b16th\b"
    | #"\b17th\b"
    | #"\b18th\b"
    | #"\b19th\b"
    | #"\b20th\b"
    | #"\b21st\b"
    | #"\b22nd\b"
    | #"\b23rd\b"
    | #"\b24th\b"
    | #"\b25th\b"
    | #"\b26th\b"
    | #"\b27th\b"
    | #"\b28th\b"
    | #"\b29th\b"
    | #"\b30th\b"
    | #"\b31st\b"
    | #"\b32nd\b"
    | #"\b33rd\b"
    | #"\b34th\b"
    | #"\b35th\b"
    | #"\b36th\b"
    | #"\b37th\b"
    | #"\b38th\b"
    | #"\b39th\b"
    | #"\b40th\b"
    | #"\b41st\b"
    | #"\b42nd\b"
    | #"\b43rd\b"
    | #"\b44th\b"
    | #"\b45th\b"
    | #"\b46th\b"
    | #"\b47th\b"
    | #"\b48th\b"
    | #"\b49th\b"
    | #"\b50th\b"
    | #"\b51st\b"
    | #"\b52nd\b"
    | #"\b53rd\b"
    | #"\b54th\b"
    | #"\b55th\b"
    | #"\b56th\b"
    | #"\b57th\b"
    | #"\b58th\b"
    | #"\b59th\b"
    | #"\b60th\b"
    | #"\b61th\b"
    | #"\b62th\b"
    | #"\b63th\b"
    | #"\b64th\b"
    | #"\b65th\b"
    | #"\b66th\b"
    | #"\b67th\b"
    | #"\b68th\b"
    | #"\b69th\b"
    | #"\b70th\b"
    | #"\b71st\b"
    | #"\b72nd\b"
    | #"\b73rd\b"
    | #"\b74th\b"
    | #"\b75th\b"
    | #"\b76th\b"
    | #"\b77th\b"
    | #"\b78th\b"
    | #"\b79th\b"
    | #"\b80th\b"
    | #"\b81st\b"
    | #"\b82nd\b"
    | #"\b83rd\b"
    | #"\b84th\b"
    | #"\b85th\b"
    | #"\b86th\b"
    | #"\b87th\b"
    | #"\b88th\b"
    | #"\b89th\b"
    | #"\b90th\b"
    | #"\b91st\b"
    | #"\b92nd\b"
    | #"\b93rd\b"
    | #"\b94th\b"
    | #"\b95th\b"
    | #"\b96th\b"
    | #"\b97th\b"
    | #"\b98th\b"
    | #"\b99th\b"
    | #"\b100th\b"
ordinal/NUMBER-DOT
    = #"\b1[.:](?=([ ,&]|$))"
    | #"\b2[.:](?=([ ,&]|$))"
    | #"\b3[.:](?=([ ,&]|$))"
    | #"\b4[.:](?=([ ,&]|$))"
    | #"\b5[.:](?=([ ,&]|$))"
    | #"\b6[.:](?=([ ,&]|$))"
    | #"\b7[.:](?=([ ,&]|$))"
    | #"\b8[.:](?=([ ,&]|$))"
    | #"\b9[.:](?=([ ,&]|$))"
    | #"\b10[.:](?=([ ,&]|$))"
    | #"\b11[.:](?=([ ,&]|$))"
    | #"\b12[.:](?=([ ,&]|$))"
    | #"\b13[.:](?=([ ,&]|$))"
    | #"\b14[.:](?=([ ,&]|$))"
    | #"\b15[.:](?=([ ,&]|$))"
    | #"\b16[.:](?=([ ,&]|$))"
    | #"\b17[.:](?=([ ,&]|$))"
    | #"\b18[.:](?=([ ,&]|$))"
    | #"\b19[.:](?=([ ,&]|$))"
    | #"\b20[.:](?=([ ,&]|$))"
    | #"\b21[.:](?=([ ,&]|$))"
    | #"\b22[.:](?=([ ,&]|$))"
    | #"\b23[.:](?=([ ,&]|$))"
    | #"\b24[.:](?=([ ,&]|$))"
    | #"\b25[.:](?=([ ,&]|$))"
    | #"\b26[.:](?=([ ,&]|$))"
    | #"\b27[.:](?=([ ,&]|$))"
    | #"\b28[.:](?=([ ,&]|$))"
    | #"\b29[.:](?=([ ,&]|$))"
    | #"\b30[.:](?=([ ,&]|$))"
    | #"\b31[.:](?=([ ,&]|$))"
    | #"\b32[.:](?=([ ,&]|$))"
    | #"\b33[.:](?=([ ,&]|$))"
    | #"\b34[.:](?=([ ,&]|$))"
    | #"\b35[.:](?=([ ,&]|$))"
    | #"\b36[.:](?=([ ,&]|$))"
    | #"\b37[.:](?=([ ,&]|$))"
    | #"\b38[.:](?=([ ,&]|$))"
    | #"\b39[.:](?=([ ,&]|$))"
    | #"\b40[.:](?=([ ,&]|$))"
    | #"\b41[.:](?=([ ,&]|$))"
    | #"\b42[.:](?=([ ,&]|$))"
    | #"\b43[.:](?=([ ,&]|$))"
    | #"\b44[.:](?=([ ,&]|$))"
    | #"\b45[.:](?=([ ,&]|$))"
    | #"\b46[.:](?=([ ,&]|$))"
    | #"\b47[.:](?=([ ,&]|$))"
    | #"\b48[.:](?=([ ,&]|$))"
    | #"\b49[.:](?=([ ,&]|$))"
    | #"\b50[.:](?=([ ,&]|$))"
    | #"\b51[.:](?=([ ,&]|$))"
    | #"\b52[.:](?=([ ,&]|$))"
    | #"\b53[.:](?=([ ,&]|$))"
    | #"\b54[.:](?=([ ,&]|$))"
    | #"\b55[.:](?=([ ,&]|$))"
    | #"\b56[.:](?=([ ,&]|$))"
    | #"\b57[.:](?=([ ,&]|$))"
    | #"\b58[.:](?=([ ,&]|$))"
    | #"\b59[.:](?=([ ,&]|$))"
    | #"\b60[.:](?=([ ,&]|$))"
    | #"\b61[.:](?=([ ,&]|$))"
    | #"\b62[.:](?=([ ,&]|$))"
    | #"\b63[.:](?=([ ,&]|$))"
    | #"\b64[.:](?=([ ,&]|$))"
    | #"\b65[.:](?=([ ,&]|$))"
    | #"\b66[.:](?=([ ,&]|$))"
    | #"\b67[.:](?=([ ,&]|$))"
    | #"\b68[.:](?=([ ,&]|$))"
    | #"\b69[.:](?=([ ,&]|$))"
    | #"\b70[.:](?=([ ,&]|$))"
    | #"\b71[.:](?=([ ,&]|$))"
    | #"\b72[.:](?=([ ,&]|$))"
    | #"\b73[.:](?=([ ,&]|$))"
    | #"\b74[.:](?=([ ,&]|$))"
    | #"\b75[.:](?=([ ,&]|$))"
    | #"\b76[.:](?=([ ,&]|$))"
    | #"\b77[.:](?=([ ,&]|$))"
    | #"\b78[.:](?=([ ,&]|$))"
    | #"\b79[.:](?=([ ,&]|$))"
    | #"\b80[.:](?=([ ,&]|$))"
    | #"\b81[.:](?=([ ,&]|$))"
    | #"\b82[.:](?=([ ,&]|$))"
    | #"\b83[.:](?=([ ,&]|$))"
    | #"\b84[.:](?=([ ,&]|$))"
    | #"\b85[.:](?=([ ,&]|$))"
    | #"\b86[.:](?=([ ,&]|$))"
    | #"\b87[.:](?=([ ,&]|$))"
    | #"\b88[.:](?=([ ,&]|$))"
    | #"\b89[.:](?=([ ,&]|$))"
    | #"\b90[.:](?=([ ,&]|$))"
    | #"\b91[.:](?=([ ,&]|$))"
    | #"\b92[.:](?=([ ,&]|$))"
    | #"\b93[.:](?=([ ,&]|$))"
    | #"\b94[.:](?=([ ,&]|$))"
    | #"\b95[.:](?=([ ,&]|$))"
    | #"\b96[.:](?=([ ,&]|$))"
    | #"\b97[.:](?=([ ,&]|$))"
    | #"\b98[.:](?=([ ,&]|$))"
    | #"\b99[.:](?=([ ,&]|$))"
    | #"\b100[.:](?=([ ,&]|$))"
ordinal/ROMAN-DOT
    = #"\bi[.:](?=([ ,&]|$))"
    | #"\bii[.:](?=([ ,&]|$))"
    | #"\biii[.:](?=([ ,&]|$))"
    | #"\biv[.:](?=([ ,&]|$))"
    | #"\biiii[.:](?=([ ,&]|$))"
    | #"\bv[.:](?=([ ,&]|$))"
    | #"\bvi[.:](?=([ ,&]|$))"
    | #"\bvii[.:](?=([ ,&]|$))"
    | #"\bviii[.:](?=([ ,&]|$))"
    | #"\bix[.:](?=([ ,&]|$))"
    | #"\bx[.:](?=([ ,&]|$))"
    | #"\bxi[.:](?=([ ,&]|$))"
    | #"\bxii[.:](?=([ ,&]|$))"
    | #"\bxiii[.:](?=([ ,&]|$))"
    | #"\bxiv[.:](?=([ ,&]|$))"
    | #"\bxv[.:](?=([ ,&]|$))"
    | #"\bxvi[.:](?=([ ,&]|$))"
    | #"\bxvii[.:](?=([ ,&]|$))"
    | #"\bxviii[.:](?=([ ,&]|$))"
    | #"\bxix[.:](?=([ ,&]|$))"
    | #"\bxx[.:](?=([ ,&]|$))"
    | #"\bxxi[.:](?=([ ,&]|$))"
    | #"\bxxii[.:](?=([ ,&]|$))"
    | #"\bxxiii[.:](?=([ ,&]|$))"
    | #"\bxxiv[.:](?=([ ,&]|$))"
    | #"\bxxv[.:](?=([ ,&]|$))"
    | #"\bxxvi[.:](?=([ ,&]|$))"
    | #"\bxxvii[.:](?=([ ,&]|$))"
    | #"\bxxviii[.:](?=([ ,&]|$))"
    | #"\bxxix[.:](?=([ ,&]|$))"
    | #"\bxxx[.:](?=([ ,&]|$))"
    | #"\bxxxi[.:](?=([ ,&]|$))"
    | #"\bxxxii[.:](?=([ ,&]|$))"
    | #"\bxxxiii[.:](?=([ ,&]|$))"
    | #"\bxxxiv[.:](?=([ ,&]|$))"
    | #"\bxxxv[.:](?=([ ,&]|$))"
    | #"\bxxxvi[.:](?=([ ,&]|$))"
    | #"\bxxxvii[.:](?=([ ,&]|$))"
    | #"\bxxxviii[.:](?=([ ,&]|$))"
    | #"\bxxxix[.:](?=([ ,&]|$))"
    | #"\bxl[.:](?=([ ,&]|$))"
    | #"\bxli[.:](?=([ ,&]|$))"
    | #"\bxlii[.:](?=([ ,&]|$))"
    | #"\bxliii[.:](?=([ ,&]|$))"
    | #"\bxliv[.:](?=([ ,&]|$))"
    | #"\bxlv[.:](?=([ ,&]|$))"
    | #"\bxlvi[.:](?=([ ,&]|$))"
    | #"\bxlvii[.:](?=([ ,&]|$))"
    | #"\bxlviii[.:](?=([ ,&]|$))"
    | #"\bxlix[.:](?=([ ,&]|$))"
    | #"\bl[.:](?=([ ,&]|$))"
    | #"\bli[.:](?=([ ,&]|$))"
    | #"\blii[.:](?=([ ,&]|$))"
    | #"\bliii[.:](?=([ ,&]|$))"
    | #"\bliv[.:](?=([ ,&]|$))"
    | #"\blv[.:](?=([ ,&]|$))"
    | #"\blvi[.:](?=([ ,&]|$))"
    | #"\blvii[.:](?=([ ,&]|$))"
    | #"\blviii[.:](?=([ ,&]|$))"
    | #"\blix[.:](?=([ ,&]|$))"
    | #"\blx[.:](?=([ ,&]|$))"
    | #"\blxi[.:](?=([ ,&]|$))"
    | #"\blxii[.:](?=([ ,&]|$))"
    | #"\blxiii[.:](?=([ ,&]|$))"
    | #"\blxiv[.:](?=([ ,&]|$))"
    | #"\blxv[.:](?=([ ,&]|$))"
    | #"\blxvi[.:](?=([ ,&]|$))"
    | #"\blxvii[.:](?=([ ,&]|$))"
    | #"\blxviii[.:](?=([ ,&]|$))"
    | #"\blxix[.:](?=([ ,&]|$))"
    | #"\blxx[.:](?=([ ,&]|$))"
    | #"\blxxi[.:](?=([ ,&]|$))"
    | #"\blxxii[.:](?=([ ,&]|$))"
    | #"\blxxiii[.:](?=([ ,&]|$))"
    | #"\blxxiv[.:](?=([ ,&]|$))"
    | #"\blxxv[.:](?=([ ,&]|$))"
    | #"\blxxvi[.:](?=([ ,&]|$))"
    | #"\blxxvii[.:](?=([ ,&]|$))"
    | #"\blxxviii[.:](?=([ ,&]|$))"
    | #"\blxxix[.:](?=([ ,&]|$))"
    | #"\blxxx[.:](?=([ ,&]|$))"
    | #"\blxxxi[.:](?=([ ,&]|$))"
    | #"\blxxxii[.:](?=([ ,&]|$))"
    | #"\blxxxiii[.:](?=([ ,&]|$))"
    | #"\blxxxiv[.:](?=([ ,&]|$))"
    | #"\blxxxv[.:](?=([ ,&]|$))"
    | #"\blxxxvi[.:](?=([ ,&]|$))"
    | #"\blxxxvii[.:](?=([ ,&]|$))"
    | #"\blxxxviii[.:](?=([ ,&]|$))"
    | #"\blxxxix[.:](?=([ ,&]|$))"
    | #"\bxc[.:](?=([ ,&]|$))"
    | #"\bxci[.:](?=([ ,&]|$))"
    | #"\bxcii[.:](?=([ ,&]|$))"
    | #"\bxciii[.:](?=([ ,&]|$))"
    | #"\bxciv[.:](?=([ ,&]|$))"
    | #"\bxcv[.:](?=([ ,&]|$))"
    | #"\bxcvi[.:](?=([ ,&]|$))"
    | #"\bxcvii[.:](?=([ ,&]|$))"
    | #"\bxcviii[.:](?=([ ,&]|$))"
    | #"\bxcix[.:](?=([ ,&]|$))"
    | #"\bc[.:](?=([ ,&]|$))"
ordinal/WORD
    = #"\bfirst\b"
    | #"\bsecond\b"
    | #"\bthird\b"
    | #"\bfourth\b"
    | #"\bfifth\b"
    | #"\bsixth\b"
    | #"\bseventh\b"
    | #"\beighth\b"
    | #"\bninth\b"
    | #"\btenth\b"
    | #"\beleventh\b"
    | #"\btwelveth\b"
    | #"\bthirteenth\b"
    | #"\bfourteenth\b"
    | #"\bfifteenth\b"
    | #"\bsixteenth\b"
    | #"\bseventeenth\b"
    | #"\beighteenth\b"
    | #"\bnineteenth\b"
    | #"\btwentieth\b"

tincture/OR
    = #"\bor\b"
    | #"\bd'or\b"
tincture/ARGENT
    = #"\bargent\b"
    | #"\bd'argent\b"
    | #"\ba[.]\b"
    | #"\bar[.]?\b"
    | #"\bsilver\b"
tincture/SABLE
    = #"\bsable\b"
    | #"\bsa[.]?\b"
tincture/AZURE
    = #"\bazure\b"
    | #"\bd'azure\b"
    | #"\baz[.]?\b"
tincture/GULES
    = #"\bgules\b"
    | #"\bgu[.]?\b"
tincture/PURPURE
    = #"\bpurpure\b"
tincture/VERT
    = #"\bvert\b"
    | #"\bve[.]?\b"
tincture/TENNE
    = #"\btenne\b"
    | #"\btenn[ée](?=([ ,&]|$))"
    | #"\btenn[ée]e\b"
tincture/ORANGE
    = #"\borange\b"
    | #"\bd'orange\b"

tincture/SANGUINE = #"\bsanguine\b"
tincture/MURREY = #"\bmurrey\b"
tincture/BLEU-CELESTE
    = #"\bbleu-+celeste\b"
    | #"\bbleu +celeste\b"
tincture/ROSE = #"\brose\b"
tincture/COPPER = #"\bcopper\b"
tincture/PROPER
    = #"\bproper\b"
    | #"\bppr[.]?\b"
tincture/WHITE = #"\bwhite\b"

tincture/BRUNATRE
    = #"\bbrunatre\b"
    | #"\bbrunâtre\b"
tincture/BUFF = #"\bbuff\b"
tincture/CARNATION
    = #"\bcarnation\b"
    | #"\bgillofer\b"
    | #"\bgillyflower\b"
    | #"\bpink\b"
    | #"\bgilly\-flower\b"

tincture/CENDREE
    = #"\bcendre[ée](?=([ ,&]|$))"
    | #"\bcendre[ée]e\b"
tincture/AMARANTH
    = #"\bamaranth\b"
    | #"\bcolumbine\b"

tincture/ERMINE
    = #"\bermine\b"
    | #"\berm[.]?\b"
    | #"\barmine\b"
    | #"\bermined\b"
    | #"\bhermine\b"
    | #"\bd'hermine\b"
    | #"\bd'herminé(?=([ ,&]|$))"
    | #"\bd'herminée\b"
    | #"\bstoat\b"

tincture/ERMINES = #"\bermines\b"
tincture/ERMINOIS = #"\berminois\b"
tincture/PEAN = #"\bpean\b"

pattern-option/BENDY
    = #"\bbendy\b"
    | #"\bbarry[- ]+bendy\b"
pattern-option/BENDY-SINISTER
    = #"\bbendy +sinister\b"
    | #"\bbendy\b" #"\bsinister\b"

partition/BARRY
    = #"\bbarry\b"
    | #"\bbarruly\b"
    | #"\bburely\b"
partition/BENDY
    = #"\bbendy\b"
    | #"\bbarry[- ]+bendy\b"
partition/BENDY-SINISTER
    = #"\bbendy +sinister\b"
    | #"\bbendy\b" #"\bsinister\b"
    | #"\bbarry[- ]+bendy +sinister\b"
    | #"\bbarry[- ]+bendy\b" #"\bsinister\b"
partition/CHEQUY
    = #"\bchequy\b"
    | #"\bchecky\b"
    | #"\bcheckie\b"
    | #"\bchecquy\b"
partition/CHEVRONNY
    = #"\bchevronny\b"
    | #"\bchevronelly\b"
    | #"\bchevrony\b"
partition/FRETTY = #"\bfretty\b"
partition/GYRONNY = #"\bg[yi]ronny\b"
partition/LOZENGY = #"\blozengy\b"
partition/FUSILY
    = #"\bfusily\b"
    | #"\bfusilly\b"
partition/MASONY
    = #"\bmasony\b"
    | #"\bmasoned\b"
    | #"\bmassoned\b"
partition/PALY
    = #"\bpaly\b"
    | #"\bvergeté(?=([ ,&]|$))"
    | #"\bvergetée\b"
partition/PAPELLONY
    = #"\bpapellony\b"
    | #"\bpappellony\b"
    | #"\bpapelonny\b"

partition/PER-BEND
    = #"\bper +bend\b"
    | #"\bparty +per +bend\b"
partition/PER-BEND-SINISTER
    = #"\bper +bend +sinister\b"
    | #"\bper +bend\b" #"\bsinister\b"
    | #"\bparty +per +bend +sinister\b"
    | #"\bparty +per +bend\b" #"\bsinister\b"
partition/PER-CHEVRON
    = #"\bper +chevron\b"
    | #"\bparty +per +chevron\b"
partition/PER-FESS
    = #"\bper +fess\b"
    | #"\bparty +per +fess\b"
partition/PER-PALE
    = #"\bper +pale\b"
    | #"\bparty +per +pale\b"
partition/PER-PILE
    = #"\bper +pile\b"
    | #"\bparty +per +pile\b"
partition/PER-SALTIRE
    = #"\bper +saltire\b"
    | #"\bparty +per +saltire\b"
partition/POTENTY = #"\bpotenty\b"
partition/QUARTERED
    = #"\bquartered\b"
    | #"\bquarterly\b"
    | #"\bparty[ -]+per[ -]+cross\b"
    | #"\bper[ -]+cross\b"
partition/TIERCED-PER-FESS = #"\btierced +per +fess\b"
partition/TIERCED-PER-PALE = #"\btierced +per +pale\b"
partition/TIERCED-PER-PALL = #"\btierced +per +pall\b"
partition/VAIRY = #"\bvairy\b"

ordinary/PALE = #"\bpales?\b"
ordinary/PALLET = #"\bpall?ets?\b"
ordinary/FESS
    = #"\bfess(es?)?\b"
    | #"\bbars?\b"
    | #"\bbarrs?\b"
    | #"\bdevices?\b"
    | #"\bdivises?\b"
    | #"\bfasces?\b"
ordinary/BARRULET
    = #"\bbarrulets?\b"
    | #"\bclosets?\b"
    | #"\btrangles?\b"
    | #"\bbarrelets?\b"

ordinary/CHIEF = #"\bchief\b"
ordinary/BASE
    = #"\bbase\b"
    | #"\bchampagne\b"
    | #"\bplain\ point\b"
ordinary/BEND
    = #"\bbends?\b"
    | #"\bbandes?\b"
ordinary/BENDLET = #"\bbendlets?\b"
ordinary/BEND-SINISTER
    = #"\bbends? +sinister\b"
    | #"\bbends?\b" #"\bsinister\b"
ordinary/BENDLET-SINISTER
    = #"\bbendlets? +sinister\b"
    | #"\bbendlets?\b" #"\bsinister\b"
ordinary/CROSS = #"\bcross(es)?\b"
ordinary/SALTIRE
    = #"\bsaltires?\b"
    | #"\bplain[ -]+saltires?\b"
    | #"\bsaltiers?\b"
    | #"\bsautoirs?\b"
ordinary/CHEVRON
    = #"\bchevrons?\b"
    | #"\bcheverons?\b"
    | #"\bchevera\b"
    | #"\bchevra\b"
ordinary/CHEVRONNEL = #"\bchevronnels?\b"
ordinary/PALL
    = #"\bpalls?\b"
    | #"\bcross[ -]+palls?\b"
    | #"\bpairles?\b"
    | #"\bcross[ -]+palls?\b"
ordinary/PILE = #"\bpiles?\b"
ordinary/GORE
    = #"\bgores?\b"
    | #"\bgoars?\b"
ordinary/QUARTER
    = #"\bquarters?\b"
    | #"\bfranc[ -]+quartiers?\b"
ordinary/CANTON
    = #"\bcantons?\b"
    | #"\bcanta\b"
ordinary/POINT
    = #"\bpoints?\b"

LABEL-POINT = #"\bpoints?\b"
STAR-POINT = #"\bpoints?\b"

ordinary/BORDURE = #"\bbordures?\b"
ordinary/ORLE
    = #"\borles?\b"
    | #"\btressures?\b"
ordinary/LABEL
    = #"\blabels?\b"
    | #"\blambels?\b"

line/STRAIGHT = #"\bstraight\b"
line/INVECTED
    = #"\binvected\b"
    | #"\benvecked\b"
    | #"\binvecked\b"
    | #"\bcannel[ée](?=([ ,&]|$))"
    | #"\bcannel[ée]e\b"
line/ENGRAILED
    = #"\bengrailed\b"
    | #"\bingrailed\b"
    | #"\bsloped\b"
line/EMBATTLED
    = #"\b([ei]m)?mbattl(ed|y)\b"
line/EMBATTLED-GRADY
    = #"\b([ei]m)?battl(ed|y) grady\b"
    | #"\b([ei]m)?battl(ed|y)-+grady\b"
    | #"\b([ei]m)?battl(ed|y)\b" #"\bgrady\b"
line/EMBATTLED-IN-CROSSES
    = #"\b([ei]m)?battl(ed|y) +in +crosses\b"
    | #"\b([ei]m)?battl(ed|y)-+in-+crosses\b"
    | #"\b([ei]m)?battl(ed|y)\b" #"\bin crosses\b"
line/POTENTY = #"\bpotenty\b"
line/INDENTED
    = #"\bindented\b"
    | #"\bendented\b"
    | #"\bdentel[ée](?=([ ,&]|$))\b"
    | #"\bdentel[ée]e\b"
line/DANCETTY
    = #"\bdancetty\b"
    | #"\bdancett[ée](?=([ ,&]|$))"
    | #"\bdancett[ée]e\b"
    | #"\bdancy\b"
    | #"\bvivr[ée](?=([ ,&]|$))"
line/WAVY
    = #"\bwavy\b"
    | #"\bwaved\b"
    | #"\bundy\b"
    | #"\bondy\b"
    | #"\boundy\b"
    | #"\bond[ée](?=([ ,&]|$))"
    | #"\bond[ée]e\b"
    | #"\bund[ée](?=([ ,&]|$))"
    | #"\bund[ée]e\b"
line/NEBULY
    = #"\bnebuly\b"
    | #"\bnebul[ée](?=([ ,&]|$))"
    | #"\bnebul[ée]e\b"
line/DOVETAILED
    = #"\bdovetailed\b"
    | #"\bdove +tailed\b"
    | #"\bdove-+tailed\b"
line/RAGULY
    = #"\braguly\b"
    | #"\braguled\b"
line/THORNY = #"\bthorny\b"
line/URDY
    = #"\burdy\b"
    | #"\burd[ée](?=([ ,&]|$))"
    | #"\burd[ée]e\b"
    | #"\bwarriated\b"
    | #"\bchampaine\b"
line/FIR-TREE-TOPPED
    = #"\bfir +tree +topped\b"
    | #"\bfir-+tree-+topped\b"
line/FIR-TWIGGED
    = #"\bfir +twigged\b"
    | #"\bfir-+twigged\b"
line/WOLF-TOOTHED
    = #"\bwolf +toothed\b"
    | #"\bwolf-+toothed\b"
line/RAYONNY
    = #"\brayonny\b"
    | #"\birradiated\b"
    | #"\bradiant\b"
    | #"\brayonnant\b"
    | #"\brayonn[ée](?=([ ,&]|$))"
    | #"\brayonn[ée]e\b"
    | #"\bflamm[ée](?=([ ,&]|$))"
    | #"\bflamm[ée]e\b"
line/ANGLED
    = #"\bangled\b"
    | #"\ben [ée]querre\b"
line/BEVILLED
    = #"\bbevilled\b"
    | #"\bbevilly\b"
    | #"\bbeviled\b"
line/ENARCHED
    = #"\benarched\b"
    | #"\bconcave\b"
    | #"\barchy\b"
    | #"\bcourb[ée](?=([ ,&]|$))"
    | #"\bcourb[ée]e\b"
    | #"\bvoût[ée](?=([ ,&]|$))"
    | #"\bvoût[ée]e\b"

HUMETTY
    = #"\bhumetty\b"
    | #"\bhaumetty\b"
    | #"\bcouped\b"
    | #"\balais[ée](?=([ ,&]|$))"
    | #"\balais[ée]e\b"
    | #"\bales[ée](?=([ ,&]|$))"
    | #"\bales[ée]e\b"
TRUNCATED
    = #"\btruncated\b"
    | #"\blopped\b"
    | #"\bsnagged\b"
    | #"\btrunked\b"
VOIDED
    = #"\bvoided\b"
    | #"\bajoure\b"
    | #"\bfalse\b"
    | #"\bvid[ée](?=([ ,&]|$))"
    | #"\bvid[ée]e\b"
ENHANCED
    = #"\benhanced\b"
    | #"\binhanced\b"
    | #"\bhauss?[ée](?=([ ,&]|$))"
    | #"\bhauss?[ée]e\b"
DEHANCED
    = #"\bdehanced\b"
    | #"\bdebased\b"
    | #"\babased\b"
    | #"\babaisse\b"
REVERSED
    = #"\breversed\b"
    | #"\binverted\b"
    | #"\btransposed\b"
    | #"\brevers[ée](?=([ ,&]|$))"
    | #"\brevers[ée]e\b"
    | #"\brenvers[ée](?=([ ,&]|$))"
    | #"\brenvers[ée]e\b"
    | #"\bvers[ée](?=([ ,&]|$))"
    | #"\bvers[ée]e\b"
THROUGHOUT
    = #"\bthroughout\b"
    | #"\bentire\b"
    | #"\bfirm\b"
    | #"\bfixed\b"
DOVETAILED = #"\bdovetailed\b"

point/DEXTER
    = #"\bdexter\b"
    | #"\bright\b"
point/SINISTER
    = #"\bsinister\b"
    | #"\bleft\b"

point/CHIEF = #"\bchief\b"
point/BASE = #"\bbase\b"
point/FESS = #"\bfess\b"
point/DEXTER-CHIEF
    = #"\bdexter[ -]chief\b"
    | #"\bdexter" #"chief\b"
point/CHIEF-DEXTER
    = #"\bchief[ -]dexter\b"
    | #"\bchief" #"dexter\b"
point/SINISTER-CHIEF
    = #"\bsinister[ -]chief\b"
    | #"\bsinister" #"chief\b"
point/CHIEF-SINISTER
    = #"\bchief[ -]sinister\b"
    | #"\bchief" #"sinister\b"
point/DEXTER-BASE
    = #"\bdexter[ -]base\b"
    | #"\bdexter" #"base\b"
point/BASE-DEXTER
    = #"\bbase[ -]dexter\b"
    | #"\bbase" #"dexter\b"
point/SINISTER-BASE
    = #"\bsinister[ -]base\b"
    | #"\bsinister" #"base\b"
point/BASE-SINISTER
    = #"\bbase[ -]sinister\b"
    | #"\bbase" #"sinister\b"
point/NOMBRIL
    = #"\bnombril\b"
point/HONOUR
    = #"\bhonour\b"
point/HOIST
    = #"\bhoist\b"
point/FLY
    = #"\bfly\b"

attitude/CADENT
    = #"\bcadent\b"
    | #"\bkicking\b"
attitude/COUCHANT
    = #"\bcouchant\b"
    | #"\bjacent\b"
attitude/COURANT
    = #"\bcourant\b"
    | #"\bat[ -]+speed\b"
    | #"\bcurrent\b"
    | #"\bcursant\b"
    | #"\bin[ -]+full[ -]+chase\b"
    | #"\bin[ -]+full[ -]+course\b"
attitude/DORMANT = #"\bdormant\b"
attitude/PASCUANT
    = #"\bpascuant\b"
    | #"\bbrowsing\b"
    | #"\bgrazing\b"
    | #"\bpaissant\b"
attitude/PASSANT
    = #"\bpassant\b"
    | #"\bambulant\b"
attitude/RAMPANT
    = #"\brampant\b"
    | #"\bforcene\b"
    | #"\bcabr[ée](?=([ ,&]|$))"
    | #"\bcareering\b"
    | #"\brearing\b"
attitude/SALIENT
    = #"\bsalient\b"
    | #"\bleaping\b"
    | #"\bsaillant\b"
    | #"\bsaltant\b"
    | #"\bspringing\b"
    | #"\bsaliant\b"
attitude/SEGREANT
    = #"\bsegreant\b"
    | #"\brampant\b" #"\bwith\b" #"\bwings\b" #"\bdisplayed\b"
    | #"\bsergreant\b"
attitude/SEJANT
    = #"\bsejant\b"
    | #"\bassis\b"
    | #"\bsejeant\b"
attitude/SEJANT-ERECT
    = #"\bsejant[ -]erect\b"
    | #"\bsejant\b" #"\berect\b"
    | #"\baccroupi\b"
attitude/STATANT
    = #"\bstatant\b"
    | #"\bat\b" #"\bbay\b"
attitude/ADDORSED
    = #"\baddorsed\b"
    | #"\badoss[ée](?=([ ,&]|$))"
    | #"\bendorsed\b"
    | #"\bindorsed\b"
    | #"\badorsed\b"
attitude/COMBATANT
    = #"\bcombatant\b"
    | #"\bcombattant\b"
    | #"\baffrontant\b"
    | #"\baffront[ée](?=([ ,&]|$))"
attitude/RESPECTANT
    = #"\brespectant\b"
    | #"\baspectant\b"
    | #"\brespecting\b" #"\beach\b" #"\bother\b"
attitude/CLOSED
    = #"\bclosed\b"
    | #"\btrussed\b"
attitude/DISPLAYED
    = #"\bdisplayed\b"
    | #"\bexpanded\b"
    | #"\bspread\b"
    | #"\bdisplay'd\b"
    | #"\bexpansed\b"
attitude/IN-HER-PIETY
    = #"\bin her piety\b"
    | #"\bin-her-piety\b"
    | #"\bpiety\b"
    | #"\bvulning\b"
attitude/RECURSANT
    = #"\brecursant\b"
attitude/ISSUANT
    = #"\bissuant\b"
    | #"\bassurgant\b"
    | #"\bissant\b"
attitude/OVERT
    = #"\bovert\b"
    | #"\babaised\b"
    | #"\bdisclosed\b"
    | #"\bhovering\b"
    | #"\blowered\b"
    | #"\bwings\b" #"\binverted\b"
    | #"\bwings\b" #"\baddorsed\b" #"\band\b" #"\binverted\b"
attitude/RISING
    = #"\brising\b"
    | #"\bascending\b"
    | #"\bessorant\b"
    | #"\blevant\b"
    | #"\bsoaring\b"
    | #"\bsurgerant\b"
    | #"\bsurgiant\b"
    | #"\bsurjeant\b"
    | #"\brousant\b"
attitude/VIGILANT = #"\bvigilant\b"
attitude/VULNING = #"\bvulning\b"
attitude/VOLANT
    = #"\bvolant\b"
    | #"\bflying\b"
    | #"\bsoarant\b"
attitude/HAURIANT
    = #"\bhauriant\b"
    | #"\bhariant\b"
    | #"\bhaurient\b"
attitude/NAIANT
    = #"\bnaiant\b"
    | #"\bnatant\b"
    | #"\bswimming\b"
    | #"\bnayant\b"
attitude/URINANT
    = #"\burinant\b"
    | #"\buriant\b"
attitude/GLISSANT
    = #"\bglissant\b"
    | #"\bondoyant\b"
attitude/NOWED = #"\bnowed\b"

facing/TO-DEXTER = #"\bto[ -]dexter\b"
facing/TO-SINISTER = #"\bto[ -]sinister\b"
facing/AFFRONTE = #"\baffronte\b"
facing/EN-ARRIERE = #"\ben[ -]arriere\b"
facing/GUARDANT
    = #"\bguardant\b"
    | #"\bgardant\b"
facing/IN-TRIAN-ASPECT
    = #"\bin trian aspect\b"
    | #"\bin-trian-aspect\b"
facing/REGUARDANT
    = #"\breguardant\b"
    | #"\bregardant\b"
tincture-modifier/ARMED = #"\barmed\b"
tincture-modifier/ATTIRED
    = #"\battired\b"
    | #"\bram[ée](?=([ ,&]|$))"
tincture-modifier/BEAKED
    = #"\bbeaked\b"
    | #"\bb[ée]qu[ée](?=([ ,&]|$))"
tincture-modifier/COMBED
    = #"\bcombed\b"
    | #"\bcrested\b"
tincture-modifier/EYED
    = #"\beyed\b"
tincture-modifier/EYED-PEACOCK
    = #"\beyed +peacock\b"
    | #"\beyed-peacock\b"
    | #"\bpeacock +eyed\b"
    | #"\bpeacock-eyed\b"
tincture-modifier/FINNED
    = #"\bfinned\b"
tincture-modifier/INCENSED
    = #"\bincensed\b"
    | #"\banim[ée](?=([ ,&]|$))"
    | #"\bwith\b" #"\bfire\b" #"\bissuing\b" #"\bout\b" #"\bof\b" #"\b(his|its|her|their)\b" #"\bmouth(s|es)?\b"
tincture-modifier/LANGUED
    = #"\blangued\b"
    | #"\blampass[ée](?=([ ,&]|$))"
tincture-modifier/LEGGED
    = #"\blegged\b"
    | #"\bmembered\b"
tincture-modifier/MANED
    = #"\bmaned\b"
    | #"\bcrined\b"
tincture-modifier/ORBED
    = #"\borbed\b"
    | #"\ballum[ée](?=([ ,&]|$))"
    | #"\banim[ée](?=([ ,&]|$))"
tincture-modifier/TAILED = #"\btailed\b"
tincture-modifier/TOOTHED = #"\btoothed\b"
tincture-modifier/UNGULED
    = #"\bunguled\b"
    | #"\bcleyed\b"
    | #"\bhoofed\b"
    | #"\bhooved\b"
    | #"\bongl[ée](?=([ ,&]|$))"
    | #"\btaloned\b"
tincture-modifier/WATTLED
    = #"\bwattled\b"
    | #"\bjawlopped\b"
    | #"\bjelloped\b"
    | #"\bjellopped\b"
    | #"\bjowlopped\b"
    | #"\bwatled\b"
tincture-modifier/WINGED
    = #"\bwinged\b"
    | #"\baisl[ée](?=([ ,&]|$))"
    | #"\bpinioned\b"
    | #"\baisle\b"
tincture-modifier/BARBED
    = #"\bbarbed\b"
    | #"\bwhiskered\b"
    | #"\bbearded\b"
tincture-modifier/BLADED
    = #"\bbladed\b"
    | #"\bstalked\b"
    | #"\btig[ée](?=([ ,&]|$))"
tincture-modifier/FRUCTED = #"\bfructed\b"
tincture-modifier/LEAVED
    = #"\bleaved\b"
    | #"\bfeuill[ée](?=([ ,&]|$))"
    | #"\bleafy\b"
    | #"\bfoliated\b"
tincture-modifier/SEEDED
    = #"\bseeded\b"
    | #"\bboutonn[ée](?=([ ,&]|$))"
tincture-modifier/SLIPPED
    = #"\bslipped\b"
    | #"\bstalked\b"
    | #"\btig[ée](?=([ ,&]|$))"
tincture-modifier/BARRED = #"\bbarred\b"
tincture-modifier/TRIMMED = #"\btrimmed\b"
tincture-modifier/CAPARISONED
    = #"\bcaparisoned\b"
    | #"\baccoutred\b"
    | #"\bfurnished\b"
    | #"\bwith\b" #"\btrappers\b"
tincture-modifier/COLLARED
    = #"\bcollared\b"
    | #"\baccol[ée](?=([ ,&]|$))"
    | #"\bgorged\b"
tincture-modifier/ERASED
    = #"\berased\b"
    | #"\beraced\b"
tincture-modifier/GARNISHED
    = #"\bgarnished\b"
    | #"\bembout[ée](?=([ ,&]|$))"
    | #"\bpurfled\b"
tincture-modifier/HANDLED
    = #"\bhandled\b"
    | #"\bemmanch[ée](?=([ ,&]|$))"
    | #"\bhafted\b"
tincture-modifier/HILTED
    = #"\bhilted\b"
    | #"\bhelved\b"
    | #"\bhilt\b"
tincture-modifier/ILLUMINATED = #"\billuminated\b"
tincture-modifier/HOODED = #"\bhooded\b"
tincture-modifier/MASONED
    = #"\bmasoned\b"
    | #"\bmassoned\b"
tincture-modifier/POMMELED = #"\bpommeled\b"
tincture-modifier/STRINGED = #"\bstringed\b"

MIRRORED = #"\bmirrored\b"
ERASED
    = #"\berased\b"
    | #"\beraced\b"
charge/ROUNDEL
    = #"\broundels?\b"
    | #"\bballs?\b"
    | #"\broundles?\b"
charge/ANNULET
    = #"\bannulets?\b"
    | #"\bcyclamors?\b"
    | #"\bfalse\b" #"\broundels?\b"
    | #"\brings?\b"
charge/BILLET = #"\bbillets?\b"
charge/ESCUTCHEON
    = #"\binescutcheons?\b"
    | #"\bescutcheons?\b"
charge/LOZENGE
    = #"\blozenges?\b"
    | #"\blozanges?\b"
    | #"\blosanges?\b"
charge/FUSIL
    = #"\bfusils?\b"
    | #"\bfus[ée]es?\b"

charge/MASCLE
    = #"\bmascles?\b"
    | #"\bmacles?\b"
charge/RUSTRE = #"\brustres?\b"
charge/STAR
    = #"\bstars?\b"
    | #"\bmullets?\b"
charge/ESTOILE
    = #"\bestoile?s?\b"
charge/CRESCENT
    = #"\bcrescents?\b"
    | #"\bcroissants?\b"
    | #"\bmoons?\b"
arrangement/PALEWISE
    = #"\bpale[ -]?wise\b"
    | #"\bpaleways\b"
arrangement/FESSWISE
    = #"\bfess[ -]?wise\b"
    | #"\bfess[ -]?ways\b"
    | #"\bbarr?[ -]?wise\b"
    | #"\bbarr?[ -]?ways\b"
arrangement/BENDWISE
    = #"\bbend[ -]?wise\b"
    | #"\bbend[ -]?ways\b"
arrangement/BENDWISE-SINISTER
    = #"\bbend[ -]?wise +sinister\b"
    | #"\bbend[ -]?wise\b" #"\bsinister\b"
    | #"\bbend[ -]?ways +sinister\b"
    | #"\bbend[ -]?ways\b" #"\bsinister\b"
arrangement/CHEVRONWISE
    = #"\bchevron[ -]?wise\b"
    | #"\bin +chevron\b"
arrangement/IN-ANNULLO
    = #"\bin +annullo\b"
arrangement/IN-ORLE = #"\bin +orle\b"
arrangement/ARRANGED
    = #"\barranged\b"
    | #"\barranged +as\b"

(* rules *)

blazon
    = root-field

charged-with
    = CHARGED? WITH

on-a
    = ON A

root-field
    = root-variation <charged-with> component (AND* components)?
    | root-variation
    | root-variation (AND* components)?
    | <"("> root-field <")">

field
    = variation <charged-with> component (AND* components)?
    | variation
    | variation (AND* components)?
    | <"("> field <")">

root-variation
    = root-plain
    | partition

variation
    = plain
    | partition

root-plain
    = tincture

plain
    = tincture
    | COUNTERCHANGED

of-the
    = OF? THE
    | IN? THE
    | LIKE? THE

tincture
    = tincture/OR
    | tincture/ARGENT
    | tincture/SABLE
    | tincture/AZURE
    | tincture/GULES
    | tincture/PURPURE
    | tincture/VERT
    | tincture/TENNE
    | tincture/ORANGE
    | tincture/SANGUINE
    | tincture/MURREY
    | tincture/BLEU-CELESTE
    | tincture/ROSE
    | tincture/COPPER
    | tincture/CARNATION
    | tincture/CENDREE
    | tincture/PROPER
    | tincture/WHITE
    | tincture/BRUNATRE
    | tincture/BUFF
    | tincture/AMARANTH
    | tincture/ERMINE
    | tincture/ERMINES
    | tincture/ERMINOIS
    | tincture/PEAN
    | <of-the> ordinal <TINCTURE>?
    | <of-the> FIELD
    | <of-the> SAME

(* used for suggestion labeling *)
partition-type
    = partition/BARRY
    | partition/BENDY
    | partition/BENDY-SINISTER
    | partition/CHEQUY
    | partition/CHEVRONNY
    | partition/FRETTY
    | partition/GYRONNY
    | partition/LOZENGY
    | partition/FUSILY
    | partition/MASONY
    | partition/PALY
    | partition/PAPELLONY
    | partition/PER-BEND
    | partition/PER-BEND-SINISTER
    | partition/PER-CHEVRON
    | partition/PER-FESS
    | partition/PER-PALE
    | partition/PER-PILE
    | partition/PER-SALTIRE
    | partition/POTENTY
    | partition/QUARTERED
    | partition/TIERCED-PER-FESS
    | partition/TIERCED-PER-PALE
    | partition/TIERCED-PER-PALL
    | partition/VAIRY

(* used for suggestion labeling *)
layout-words
    = OF
    | X
    | TIMES
    | TRACTS

horizontal-layout
    = amount

vertical-layout
    = vertical-layout-implicit
    | vertical-layout-explicit

vertical-layout-implicit
    = amount

vertical-layout-explicit
    = amount TRACTS

layout-times
    = X
    | TIMES
    | AND

layout
    = horizontal-layout
    | vertical-layout-explicit
    | horizontal-layout layout-times? vertical-layout
    | vertical-layout-explicit layout-times? horizontal-layout

field-location
    = point/DEXTER
    | point/SINISTER
    | point/CHIEF
    | point/BASE
    | point/FESS
    | point/DEXTER-CHIEF
    | point/CHIEF-DEXTER
    | point/SINISTER-CHIEF
    | point/CHIEF-SINISTER
    | point/DEXTER-BASE
    | point/BASE-DEXTER
    | point/SINISTER-BASE
    | point/BASE-SINISTER

field-reference
    = (<IN> | <WITH>)? <THE>? ordinal-including-dot <FIELD>?
    | (<IN> | <WITH>)? <THE>? field-location <FIELD>?

partition-field
    = (field-reference (AND* field-reference)*)? root-field

partition-field-plain
    = (field-reference (AND* field-reference)*)? root-plain

<pattern-option>
    = pattern-option/BENDY
    | pattern-option/BENDY-SINISTER

partition
    = partition/PER-PALE
      line?
      partition-field AND+ partition-field

    | (partition/PER-FESS
       | partition/PER-BEND
       | partition/PER-BEND-SINISTER)
      (enhanced-dehanced* line?
       | line? enhanced-dehanced*)
      partition-field AND+ partition-field

    | partition/PER-CHEVRON
      (enhanced-dehanced-reversed* line?
       | line? enhanced-dehanced-reversed*)
      partition-field AND+ partition-field

    | partition/PER-PILE
      (REVERSED? (line (AND+ line)?)?
       | (line (AND+ line)?)? REVERSED?)
      partition-field AND+ partition-field (AND+ partition-field)?

    | partition/TIERCED-PER-PALE
      (line (AND+ line)?)?
      partition-field AND+ partition-field (AND+ partition-field)?

    | partition/TIERCED-PER-FESS
      (enhanced-dehanced* (line (AND+ line)?)?
       | (line (AND+ line)?)? enhanced-dehanced*)
      partition-field AND+ partition-field (AND+ partition-field)?

    | partition/TIERCED-PER-PALL
      (enhanced-dehanced-reversed* (line (AND+ line)? (AND+ line)?)?
       | (line (AND+ line)? (AND+ line)?)? enhanced-dehanced-reversed*)
      partition-field AND+ partition-field (AND+ partition-field)?

    | (partition/PER-SALTIRE
       | partition/QUARTERED)
      (enhanced-dehanced* line?
       | line? enhanced-dehanced*)
      partition-field AND+ partition-field (AND+ partition-field)? (AND+ partition-field)?

    | partition/GYRONNY
      (OF? horizontal-layout)?
      (enhanced-dehanced* line?
       | line? enhanced-dehanced*)
      partition-field AND+ partition-field (AND+ partition-field)? (AND+ partition-field)? (AND+ partition-field)? (AND+ partition-field)? (AND+ partition-field)? (AND+ partition-field)?

    | partition/QUARTERED
      (OF? layout)?
      enhanced-dehanced*
      partition-field AND+ partition-field (AND+ partition-field)*

    | partition/CHEQUY
      (OF? layout)?
      partition-field-plain AND+ partition-field-plain (AND+ partition-field-plain)*

    | (partition/LOZENGY
       | partition/FUSILY
       | partition/VAIRY
       | partition/POTENTY
       | partition/PAPELLONY
       | partition/MASONY
       | partition/FRETTY)
      pattern-option?
      OF? layout?
      partition-field-plain AND+ partition-field-plain

    | partition-field-plain
      (partition/PAPELLONY
       | partition/MASONY
       | partition/FRETTY)
      OF? layout?
      partition-field-plain

    | partition/PALY
      (OF? horizontal-layout)?
      line? partition-field AND+ partition-field

    | (partition/BARRY
       | partition/BENDY
       | partition/BENDY-SINISTER
       | partition/CHEVRONNY)
      (OF? vertical-layout)?
      line? partition-field AND+ partition-field

components
    = component (AND* component)*

component
    = ordinary-group
    | ordinary-with-components
    | charge-group
    | semy

number-word
    = number/DIGIT-WORD
    | <A>? number/MULTI-WORD
    | number/TEEN-WORD
    | number/MULTIPLE-OF-TEN-WORD
    | number/MULTIPLE-OF-TEN-WORD #"-?" number/DIGIT-WORD

ordinal
    = ordinal/NUMBER
    | ordinal/WORD

ordinal-including-dot
    = ordinal/NUMBER
    | ordinal/WORD
    | ordinal/NUMBER-DOT
    | ordinal/ROMAN-DOT

amount
    = A
    | number/NUMBER
    | number-word

<between-or-with>
    = BETWEEN
    | WITH
cottise
    = (line (AND+ line)?)? field fimbriation?
cottising
    = between-or-with? COTTISED WITH? cottise
    | between-or-with? COTTISED WITH? cottise AND+ cottise
    | between-or-with? DOUBLY COTTISED WITH? cottise
    | between-or-with? DOUBLY COTTISED WITH? cottise AND+ cottise

(* used for suggestion labeling *)
cottising-word
    = COTTISED
    | DOUBLY
    | BETWEEN
    | WITH

ordinary-group
    = amount? ordinary

ordinary-with-components
    = <on-a> ordinary components
    | <"("> <on-a> ordinary components <")">

(* used for suggestion labeling *)
ordinary-type
    = ordinary/BARRULET
    | ordinary/BASE
    | ordinary/BEND
    | ordinary/BENDLET
    | ordinary/BEND-SINISTER
    | ordinary/BENDLET-SINISTER
    | ordinary/BORDURE
    | ordinary/CHEVRON
    | ordinary/CHEVRONNEL
    | ordinary/CHIEF
    | ordinary/CROSS
    | ordinary/FESS
    | ordinary/GORE
    | ordinary/LABEL
    | ordinary/ORLE
    | ordinary/PALE
    | ordinary/PALL
    | ordinary/PALLET
    | ordinary/PILE
    | ordinary/POINT
    | ordinary/CANTON
    | ordinary/QUARTER
    | ordinary/SALTIRE

(* used for suggestion labeling *)
ordinary-option
    = humetty-voided
    | enhanced-dehanced
    | reversed-throughout

<humetty-voided>
    = AND* HUMETTY
    | AND* VOIDED

<humetty-voided-truncated-dovetailed>
    = humetty-voided
    | AND* TRUNCATED
    | AND* DOVETAILED

<enhanced-dehanced>
    = AND* ENHANCED
    | AND* DEHANCED

<enhanced-dehanced-reversed>
    = enhanced-dehanced
    | AND* REVERSED

<reversed-throughout>
    = AND* REVERSED
    | AND* THROUGHOUT

<humetty-voided-enhanced-dehanced>
    = humetty-voided
    | enhanced-dehanced

<humetty-voided-enhanced-dehanced-reversed>
    = humetty-voided
    | enhanced-dehanced
    | AND* REVERSED

<humetty-voided-reversed-throughout>
    = humetty-voided
    | reversed-throughout

<dexter-sinister>
    = AND* point/DEXTER
    | AND* point/SINISTER

<humetty-voided-enhanced-dehanced-dexter-sinister>
    = humetty-voided
    | enhanced-dehanced
    | dexter-sinister

<of-or-with>
    = OF
    | WITH

label-points
    = (of-or-with? amount LABEL-POINT?)

ordinary
    = ordinary/LABEL
      (humetty-voided-truncated-dovetailed* label-points?
       | label-points? humetty-voided-truncated-dovetailed*)
      (fimbriation? field
       | field? fimbriation)

    | ordinary/BORDURE
      line?
      field fimbriation?

    | ordinary/GORE
      dexter-sinister?
      line?
      field fimbriation?

    | (ordinary/CHIEF
       | ordinary/BASE)
      (humetty-voided-enhanced-dehanced* line?
       | line? humetty-voided-enhanced-dehanced*)
      field fimbriation?
      cottising?

    | ordinary/POINT
      (humetty-voided-enhanced-dehanced-dexter-sinister* line?
       | line? humetty-voided-enhanced-dehanced-dexter-sinister*)
      field fimbriation?
      cottising?

    | ordinary/ORLE
      (line (AND+ line)?)?
      field fimbriation?

    | (ordinary/CROSS
       | ordinary/SALTIRE)
      (humetty-voided-enhanced-dehanced* (line (AND+ line)?)?
       | (line (AND+ line)?)? humetty-voided-enhanced-dehanced*)
      field fimbriation?
      cottising?

    | (ordinary/QUARTER
       | ordinary/CANTON)
      (humetty-voided-enhanced-dehanced-dexter-sinister* (line (AND+ line)?)?
       | (line (AND+ line)?)? humetty-voided-enhanced-dehanced-dexter-sinister*)
      field fimbriation?
      cottising?

    | ordinary/PILE
      (humetty-voided-reversed-throughout* (line (AND+ line)?)?
       | (line (AND+ line)?)? humetty-voided-reversed-throughout*)
      field fimbriation?
      cottising?

    | (ordinary/PALE
       | ordinary/PALLET)
      (humetty-voided* (line (AND+ line)?)?
       | (line (AND+ line)?)? humetty-voided*)
      field fimbriation?
      (cottising (AND? cottising)?)?

    | (ordinary/FESS
       | ordinary/BARRULET
       | ordinary/BEND
       | ordinary/BENDLET
       | ordinary/BEND-SINISTER
       | ordinary/BENDLET-SINISTER)
      (humetty-voided-enhanced-dehanced* (line (AND+ line)?)?
       | (line (AND+ line)?)? humetty-voided-enhanced-dehanced*)
      field fimbriation?
      (cottising (AND? cottising)?)?

    | (ordinary/PALL
       | ordinary/CHEVRON
       | ordinary/CHEVRONNEL)
      (humetty-voided-enhanced-dehanced-reversed* (line (AND+ line (AND+ line)?)?)?
       | (line (AND+ line (AND+ line)?)?)? humetty-voided-enhanced-dehanced-reversed*)
      field fimbriation?
      (cottising (AND? cottising (AND? cottising)?)?)?

line
    = line-type fimbriation?
    | fimbriation

line-type
    = line/STRAIGHT
    | line/INVECTED
    | line/ENGRAILED
    | line/EMBATTLED
    | line/EMBATTLED-GRADY
    | line/EMBATTLED-IN-CROSSES
    | line/POTENTY
    | line/INDENTED
    | line/DANCETTY
    | line/WAVY
    | line/NEBULY
    | line/DOVETAILED
    | line/RAGULY
    | line/THORNY
    | line/URDY
    | line/FIR-TREE-TOPPED
    | line/FIR-TWIGGED
    | line/WOLF-TOOTHED
    | line/RAYONNY
    | line/ANGLED
    | line/BEVILLED
    | line/ENARCHED

fimbriation
    = FIMBRIATED of-or-with? tincture
    | FIMBRIATED of-or-with? tincture AND? tincture

<charge-location-point>
    = point/DEXTER
    | point/SINISTER
    | point/CHIEF
    | point/BASE
    | point/FESS
    | point/HONOUR
    | point/NOMBRIL
    | point/HOIST
    | point/FLY

charge-location
    = (IN | AT) charge-location-point POINT?

charge-group
    = charge-location? amount? charge-without-fimbriation
      (charge-arrangement? fimbriation? field tincture-modifier*
       | charge-arrangement? field fimbriation? tincture-modifier*
       | charge-arrangement? field tincture-modifier* fimbriation?

       | charge-arrangement? tincture-modifier* fimbriation? field
       | charge-arrangement? tincture-modifier* field fimbriation?

       | fimbriation? field tincture-modifier* charge-arrangement?
       | field fimbriation? tincture-modifier* charge-arrangement?
       | field tincture-modifier* fimbriation? charge-arrangement?

       | fimbriation? field charge-arrangement? tincture-modifier*
       | field fimbriation? charge-arrangement? tincture-modifier*
       | field charge-arrangement? fimbriation? tincture-modifier*
       | field charge-arrangement? tincture-modifier* fimbriation?

       | fimbriation? tincture-modifier* field charge-arrangement?
       | tincture-modifier* fimbriation? field charge-arrangement?
       | tincture-modifier* field fimbriation? charge-arrangement?

       | fimbriation? tincture-modifier* charge-arrangement? field
       | tincture-modifier* fimbriation? charge-arrangement? field
       | tincture-modifier* charge-arrangement? fimbriation? field
       | tincture-modifier* charge-arrangement? field fimbriation?)

semy
    = <A>? <SEMY> <of-or-with>? layout? charge-without-fimbriation fimbriation? field tincture-modifier*
    | <A>? <SEMY> <of-or-with>? layout? charge-without-fimbriation field fimbriation? tincture-modifier*
    | <A>? <SEMY> <of-or-with>? layout? charge-without-fimbriation field tincture-modifier* fimbriation?
    | <A>? <SEMY> <of-or-with>? layout? charge-without-fimbriation fimbriation? tincture-modifier* field
    | <A>? <SEMY> <of-or-with>? layout? charge-without-fimbriation tincture-modifier* fimbriation? field
    | <A>? <SEMY> <of-or-with>? layout? charge-without-fimbriation tincture-modifier* field fimbriation?

charge-without-fimbriation
    = charge-standard
    | charge-other

charge
    = charge-without-fimbriation fimbriation?

charge-arrangement
    = arrangement/PALEWISE
    | arrangement/FESSWISE
    | arrangement/BENDWISE
    | arrangement/BENDWISE-SINISTER
    | arrangement/CHEVRONWISE
    | arrangement/IN-ANNULLO
    | arrangement/IN-ORLE
    | charge-grid

charge-grid
    = arrangement/ARRANGED? amount (AND? amount)*

(* used for suggestion labeling *)
charge-option
    = mirrored-reversed

<mirrored-reversed>
    = AND* MIRRORED
    | AND* REVERSED

star-points
    = (of-or-with? amount STAR-POINT?)

(* used for bad charge type only *)
charge-standard-type
    = charge/ROUNDEL
    | charge/ANNULET
    | charge/BILLET
    | charge/ESCUTCHEON
    | charge/LOZENGE
    | charge/FUSIL
    | charge/MASCLE
    | charge/RUSTRE
    | charge/STAR
    | charge/ESTOILE
    | charge/CRESCENT

charge-standard
    = charge/ROUNDEL
    | charge/ANNULET
    | charge/BILLET
    | charge/ESCUTCHEON mirrored-reversed*
    | charge/LOZENGE
    | charge/FUSIL
    | charge/MASCLE
    | charge/RUSTRE
    | (charge/STAR
       | charge/ESTOILE)
      (star-points? REVERSED?
       | REVERSED? star-points?)
    | charge/CRESCENT REVERSED?

(* need one of them to have a valid charge-other-type rule,
   it will be overwritten when charges have been loaded, if
   it contains lion as well *)
charge-other-type/lion
    = #'\blion\b'
    | #'\blions\b'

charge-other-type
    = charge-other-type/lion

charge-other
    = charge-other-type AND* attitude? AND* facing? mirrored-reversed*

attitude
    = attitude/CADENT
    | attitude/COUCHANT
    | attitude/COURANT
    | attitude/DORMANT
    | attitude/PASCUANT
    | attitude/PASSANT
    | attitude/RAMPANT
    | attitude/SALIENT
    | attitude/SEGREANT
    | attitude/SEJANT
    | attitude/SEJANT-ERECT
    | attitude/STATANT
    | attitude/ADDORSED
    | attitude/COMBATANT
    | attitude/RESPECTANT
    | attitude/CLOSED
    | attitude/DISPLAYED
    | attitude/IN-HER-PIETY
    | attitude/ISSUANT
    | attitude/OVERT
    | attitude/RECURSANT
    | attitude/RISING
    | attitude/VIGILANT
    | attitude/VOLANT
    | attitude/VULNING
    | attitude/HAURIANT
    | attitude/NAIANT
    | attitude/URINANT
    | attitude/GLISSANT
    | attitude/NOWED

facing
    = facing/TO-DEXTER
    | facing/TO-SINISTER
    | facing/AFFRONTE
    | facing/EN-ARRIERE
    | facing/GUARDANT
    | facing/IN-TRIAN-ASPECT
    | facing/REGUARDANT

tincture-modifier-type
    = tincture-modifier/ARMED
    | tincture-modifier/ATTIRED
    | tincture-modifier/BEAKED
    | tincture-modifier/COMBED
    | tincture-modifier/EYED
    | tincture-modifier/EYED-PEACOCK
    | tincture-modifier/FINNED
    | tincture-modifier/INCENSED
    | tincture-modifier/LANGUED
    | tincture-modifier/LEGGED
    | tincture-modifier/MANED
    | tincture-modifier/ORBED
    | tincture-modifier/TAILED
    | tincture-modifier/TOOTHED
    | tincture-modifier/UNGULED
    | tincture-modifier/WATTLED
    | tincture-modifier/WINGED
    | tincture-modifier/BARBED
    | tincture-modifier/BLADED
    | tincture-modifier/FRUCTED
    | tincture-modifier/LEAVED
    | tincture-modifier/SEEDED
    | tincture-modifier/SLIPPED
    | tincture-modifier/BARRED
    | tincture-modifier/TRIMMED
    | tincture-modifier/CAPARISONED
    | tincture-modifier/COLLARED
    | tincture-modifier/ERASED
    | tincture-modifier/GARNISHED
    | tincture-modifier/HANDLED
    | tincture-modifier/HILTED
    | tincture-modifier/ILLUMINATED
    | tincture-modifier/HOODED
    | tincture-modifier/MASONED
    | tincture-modifier/POMMELED
    | tincture-modifier/STRINGED

tincture-modifier
    = (AND* tincture-modifier-type)+ tincture

(* used to filter out badly named charges *)
bad-charge-type
    = ordinary-type
    | partition-type
    | line-type
    | charge-standard-type
    | amount
    | ordinal-including-dot
    | humetty-voided-truncated-dovetailed
    | enhanced-dehanced
    | reversed-throughout
    | mirrored-reversed
    | dexter-sinister
    | FIMBRIATED
    | tincture
    | charge-arrangement
    | attitude
    | facing
    | field-location
    | tincture-modifier-type
    | A
    | AND
    | IN
    | OF
    | THE
    | LIKE
    | WITH
    | CHARGED
    | TRACTS
    | X
    | TIMES
    | TINCTURE
    | FIELD
    | SAME
    | DOUBLY
    | BETWEEN
    | COTTISED
    | SEMY
